import React from 'react';
import Document, {Head, Html, Main, NextScript} from 'next/document';

class MyDocument extends Document {
    render() {
        return (
            <Html className='main'>
                <Head>
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    {/*<title></title>*/}
                    {/*<meta name="description" content="Generated by create next app"/>*/}
                    {/*<link rel="icon" href="/favicon.ico"/>*/}
                </Head>
                <body>
                    <Main/>
                    <NextScript/>
                </body>
            </Html>
        );
    }
}

export default MyDocument;
